services:
  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - "8000:80"
    volumes:
      - /root/med/nginx.conf:/etc/nginx/templates/nginx.conf:ro
      - /root/med/medoc/static:/www/medoc/static:ro
      - /root/med/medoc/media:/www/medoc/media:ro
      - /root/sup/medoc/static:/www/sup/static:ro
    environment:
      - SUP_CONTAINER
      - SUP_DOMAIN
      - MEDOC_CONTAINER
      - MEDOC_DOMAIN