version: "3.8"

x-app:
  &base-app-conf
  image: alta7700/claims:${APP_VERSION}
  restart: always
  volumes:
    - ./app.env:/app/.env:ro
    - ./db.sqlite3:/app/db.sqlite3:rw
    - ./data/static/:/app/static/:rw

services:
  app:
    <<: *base-app-conf
    container_name: claims-app
    ports:
      - "8000:8000"
    command: [".venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000", '--noreload']

  tgbot:
    <<: *base-app-conf
    container_name: claims-tgbot
    command: [".venv/bin/python", "manage.py", "polling"]

  redis:
    container_name: claims-redis
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1

  nginx:
    container_name: claims-nginx
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:ro
      - ./data/static/:/www/app/static/:ro
    ports:
      - "${CLAIMS_PORT}:80"
    depends_on:
      - app
